# This playbook is meant to provision a new computer.
# Run with: ansible-playbook -i , provision.yml

---
- name: Provision a machine.
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Add Virtualbox server.
    apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian {{ hostvars[inventory_hostname]["ansible_distribution_release"] }} contrib' state=present
    register: ppa
    sudo: yes

  - name: Add repository keys.
    apt_key: keyserver=keyserver.ubuntu.com id={{ item }}
    register: ppa
    sudo: yes
    with_items:
      - 54422A4B98AB5139  # Virtualbox

  - name: Add PPAs.
    apt_repository: repo='{{ item }}'
    sudo: yes
    register: ppa
    with_items:
      - ppa:webupd8team/java
      - ppa:fish-shell/release-2
      - ppa:tmate.io/archive

  - name: Update the apt cache.
    apt: update_cache=yes
    sudo: yes
    when: ppa.changed

  - name: Install Mac packages.
    apt: name={{ item }}
    sudo: yes
    with_items:
     - macfanctld
    when: '"Apple" in hostvars[inventory_hostname]["ansible_system_vendor"]'

  - name: Install packages.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - adobe-flashplugin
      - libopencv-dev
      - opencv-data
      - python-opencv
      - vim-common
      - vim-gtk
      - vim-gui-common
      - vim-runtime
      - vim-tiny
      - virtualenv
      - virtualenvwrapper


  - name: Install programming languages.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - build-essential
      - afnix
      - algol68g
      - aplus-fsf
      - asymptote
      - ats2-lang
      - bash
      - bc
      - bf
      - bsdgames
      - cduce
      - clisp
      - clojure1.6
      - cmake
      - coffeescript
      - dc
      - ecere-dev
      - elixir
      - emacs24
      - erlang
      - f2c
      - fp-compiler
      - fsharp
      - g++
      - gambas3-script
      - gap
      - gauche
      - gawk
      - gcc
      - gdc
      - genius
      - gforth
      - gfortran
      - ghc
      - ghostscript
      - gnat
      - gnu-smalltalk
      - gnuplot
      - gobjc
      - golang
      - gpt
      - gri
      - groff
      - groovy
      - haxe
      - icont
      - iconx
      - intercal
      - iverilog
      - jasmin-sable
      - jq
      - julia
      - libgd-dev
      - libpng12-dev
      - lisaac
      - llvm
      - lua5.3
      - make
      - maxima
      - minizinc
      - mlton
      - mono-devel
      - mono-mcs
      - mono-vbnc
      - nasm
      - neko
      - nickle
      - nim
      - ocaml
      - octave
      - open-cobol
      - openjdk-8-jdk
      - pari-gp
      - parrot
      - perl
      - php-cli
      - pike8.0
      - python
      - r-base
      - ratfor
      - regina-rexx
      - rhino
      - ruby
      - scala
      - scilab
      - slsh
      - swi-prolog
      - tcl
      - ucblogo
      - valac
      - xsltproc
      - yorick
      - zoem
