# This playbook is meant to provision a new computer.
# Run with: ansible-playbook -i , provision.yml

---
- name: Provision a machine.
  hosts: 127.0.0.1
  connection: local
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list
  tasks:
  - include: tasks/languages.yml

  - name: Does the Google apt file exist?
    command: test -f {{apt_file}}
    register: google_apt_exists
    ignore_errors: True

  - name: Add Google Chrome key
    shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    when: google_apt_exists.rc == 1

  - name: Add Google Chrome repo
    copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{apt_file}} owner=root group=root mode=644
    when: google_apt_exists.rc == 1

  - name: Update apt cache
    apt: update_cache=yes
    when: google_apt_exists.rc == 1

  - name: Install Google Chrome
    apt: pkg=google-chrome-stable state=installed

  - name: Update the apt cache.
    apt: update_cache=yes
    sudo: yes

  - name: Install system packages.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - openssh-server
      - stow
      - htop

  - name: Install desktop environment.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - gnome
      - gnome-tweak-tool

  - name: Install misc packages.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - flashplugin-installer
      - bzip2
      - libzip-dev

  - name: Install graphics libraries
    apt: name={{ item }}
    sudo: yes
    with_items:
      - libsdl1.2debian 
      - libsdl-image1.2 
      - libsdl-ttf2.0-0
      - freeglut3-dev

  - name: Configure git
    git_config: name={{ item.name }} value={{ item.value }} scope=global
    become: yes
    become_user: mcsmash
    with_items:
      - {name: user.email, value: "beachc@gmail.com"}
      - {name: user.name, value: "Casey Beach"}

  - name: Install development tools.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - vim-common
      - vim-gtk
      - vim-gui-common
      - vim-runtime
      - vim-tiny
      - build-essential
      - libopencv-dev
      - opencv-data
      - python-opencv
      - virtualenv
      - virtualenvwrapper
      - autoconf
      - sbt
      - screen
      - sloccount

