# This playbook is meant to provision a new computer.
# Run with: ansible-playbook -i , provision.yml

---
- name: Provision a machine.
  hosts: 127.0.0.1
  connection: local
  tasks:

  - name: Update the apt cache.
    apt: update_cache=yes
    sudo: yes

  - name: Install Mac packages.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - macfanctld
    when: '"Apple" in hostvars[inventory_hostname]["ansible_system_vendor"]'

  - name: Install system packages.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - openssh-server
      - stow

  - name: Install desktop environment.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - gnome
      - gnome-tweak-tool

  - name: Install misc packages.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - flashplugin-installer
      - bzip2
      - libzip

  - name: Install graphics libraries
    apt: name={{ item }}
    sudo: yes
    with_items:
      - libsdl1.2debian 
      - libsdl-image1.2 
      - libsdl-ttf2.0-0
      - freeglut3-dev

  - name: Install development tools.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - vim-common
      - vim-gtk
      - vim-gui-common
      - vim-runtime
      - vim-tiny
      - build-essential
      - libopencv-dev
      - opencv-data
      - python-opencv
      - virtualenv
      - virtualenvwrapper
      - autoconf
      - sbt
      - screen
      - sloccount

  - name: Install programming languages.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - afnix
      - algol68g
      - aplus-fsf
      - asymptote
      - ats2-lang
      - bc
      - bf
      - bsdgames
      - cduce
      - clisp
      - clojure1.6
      - cmake
      - coffeescript
      - dc
      - ecere-dev
      - elixir
      - emacs24
      - erlang
      - f2c
      - fp-compiler
      - fsharp
      - g++
      - gambas3-script
      - gap
      - gauche
      - gawk
      - gcc
      - gdc
      - genius
      - gforth
      - gfortran
      - ghc
      - ghostscript
      - gnat
      - gnu-smalltalk
      - gnuplot
      - gobjc
      - golang
      - gpt
      - gri
      - groff
      - groovy
      - haxe
      - icont
      - iconx
      - intercal
      - iverilog
      - jasmin-sable
      - jq
      - julia
      - libgd-dev
      - libpng12-dev
      - lisaac
      - llvm
      - lua5.3
      - make
      - maxima
      - minizinc
      - mlton
      - mono-devel
      - mono-mcs
      - mono-vbnc
      - nasm
      - neko
      - nickle
      - nim
      - ocaml
      - octave
      - open-cobol
      - openjdk-8-jdk
      - pari-gp
      - parrot
      - perl
      - php-cli
      - pike8.0
      - python
      - r-base
      - ratfor
      - regina-rexx
      - rhino
      - ruby
      - scala
      - scilab
      - slsh
      - swi-prolog
      - tcl
      - ucblogo
      - valac
      - xsltproc
      - yorick
      - zoem
