---
  # List of languages shamelessly stolen from the quine relay.
  - name: Install programming languages.
    apt: name={{ item }}
    sudo: yes
    with_items:
      - afnix
      - algol68g
      - aplus-fsf
      - asymptote
      - ats2-lang
      - bc
      - bf
      - bsdgames
      - cduce
      - clisp
      - clojure1.6
      - cmake
      - coffeescript
      - dc
      - ecere-dev
      - elixir
      - emacs24
      - erlang
      - f2c
      - fp-compiler
      - fsharp
      - g++
      - gambas3-script
      - gap
      - gauche
      - gawk
      - gcc
      - gdc
      - genius
      - gforth
      - gfortran
      - ghc
      - ghostscript
      - gnat
      - gnu-smalltalk
      - gnuplot
      - gobjc
      - golang
      - gpt
      - gri
      - groff
      - groovy
      - haxe
      - icont
      - iconx
      - intercal
      - iverilog
      - jasmin-sable
      - jq
      - julia
      - libgd-dev
      - libpng12-dev
      - lisaac
      - llvm
      - lua5.3
      - make
      - maxima
      - minizinc
      - mlton
      - mono-devel
      - mono-mcs
      - mono-vbnc
      - nasm
      - neko
      - nickle
      - nim
      - ocaml
      - octave
      - open-cobol
      - openjdk-8-jdk
      - pari-gp
      - parrot
      - perl
      - php-cli
      - pike8.0
      - python
      - r-base
      - ratfor
      - regina-rexx
      - rhino
      - ruby
      - scala
      - scilab
      - slsh
      - swi-prolog
      - tcl
      - ucblogo
      - valac
      - xsltproc
      - yorick
      - zoem
