---
# Author: Andrew Veklichev, 
#         https://github.com/malk/ansible-java8-oracle/blob/master/tasks/main.yml
- name: Install add-apt-repostory
  sudo: yes
  apt: name=software-properties-common state=latest

- name: Add Oracle Java Repository
  sudo: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 7 License
  sudo: yes
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
  - oracle-java7-installer
  - ca-certificates

- name: Accept Java 8 License
  sudo: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
  - oracle-java8-installer
  - oracle-java7-installer
  - ca-certificates
  - oracle-java8-set-default
